### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by garimss** [Fyusion/LLFF#12]
Can I install this on windows?

**Comment by bmild** [comment]
I haven't tried installing on windows. Hopefully most of the steps in the [manual installation](https://github.com/Fyusion/LLFF#manual-installation) about installing the Python packages and Tensorflow/CUDA can be made to work, then you can run inference to generate MPIs and use the Tensorflow renderer to synthesize make new views. 

However, compiling and running the OpenGL viewer and CUDA renderer might be harder.

**Comment by EdisonBing** [comment]
working in Conda , windows 10 & VS2017 with additional install of cygwin (avoids issues with unix commands) and imagemagick for post processing .  OpenGL viewer will require separate compilation of gflw before compiling , once compiled link dependencies in opengl_viewer

**Comment by Pascal66** [comment]
@BingEdison Can you provide steps for Conda ?  (and Imagemagick ) ?
As both are needed by needed by [nerf](https://github.com/bmild/nerf), wich use conda, it  can be  very usefull
Thank you
