### ISSUE TITLE
Depthmaps

### ISSUE THREAD

**Issue by Tetsujinfr** [Fyusion/LLFF#14]
Hi, can your model generate accurate depth maps estimates for each of the input images, or one depth map view of the scene?

**Comment by bmild** [comment]
If you check the folders containing the MPI data after running `imgs2mpis.py`, each folder will additionally have a `disps.png` disparity map corresponding to that input image. So one per input.

**Comment by Tetsujinfr** [comment]
Ok thanks. Closing this thread.
