### ISSUE TITLE
CUDA error when running demo.sh/imgs2poses.py

### ISSUE THREAD

**Issue by hangg7** [Fyusion/LLFF#2]
Hi authors, thanks for open-sourcing the code of your amazing paper! I've been encountering with a few issues when trying to run through your demo.

I have followed your README to install the provided `nvidia-docker`. But it seems that when running `demo.sh` inside of the docker, CUDA errors exist. More specifically, when running this [line](https://github.com/Fyusion/LLFF/blob/93e9f95f47ac4e23eef932f8c3f46362d4a7781d/demo.sh#L2), program complaints about "PyramidCU::GenerateFeatureList: an illegal memory access was encountered". I've prepared my running log after both [with](https://github.com/Fyusion/LLFF/files/3144780/demo.imgs2poses_cuda-memcheck.log) and [without](https://github.com/Fyusion/LLFF/files/3144779/demo.imgs2poses.log) `cuda-memcheck` for debugging purpose. Could you please help me identify where could possibly go wrong? 

I'm using RTX 2080 Ti + cuda-10.1 + NVIDIA driver 418.39 on Ubuntu 18.04. Not sure if being too updated could be the problem.

**Comment by rodrygojose** [comment]
Hi @hangg7 , do you have more than one GPU on your machine?
Could you please set the environment variable `CUDA_VISIBLE_DEVICES`.

**Comment by hangg7** [comment]
> Hi @hangg7 , do you have more than one GPU on your machine?
> Could you please set the environment variable `CUDA_VISIBLE_DEVICES`.

Sweet!

```sh
CUDA_VISIBLE_DEVICES=0 bash demo.sh
``` 
perfectly fixed my issue. Maybe it's also worth updating the README as well? Since no such instructions are currently listed.

Closing now, and thanks for such a quick response!
