### ISSUE TITLE
Skipping the colmap

### ISSUE THREAD

**Issue by bolemebrige** [Fyusion/LLFF#22]
Since colmap is not able to register some pictures and I have data abut camera intrinsic and extrinsic matrices because I'm testing it on MPEG materials, I would like to skip it. Is colmap necessary in this case and can you please explain me how to insert these parameters in the code? 
Thanks!

**Comment by bmild** [comment]
You can skip the colmap step in this case. For info about how to use the intrinsic and extrinsic matrices to create the `poses_bounds.npy` file, [see this](https://github.com/Fyusion/LLFF/issues/10#issuecomment-514406658)
