### ISSUE TITLE
depth map

### ISSUE THREAD

**Issue by yzpick** [Fyusion/LLFF#23]
Hi, very impressive work! can you please explain a little bit more about how you generate the disparity/depth maps?
BTW, I pulled out the raw data of mpis[i].disps, looks like it is not the depth or the disparity (the unit does not match). What should I do to recover the meaningful values?

Thanks!

**Comment by bmild** [comment]
Those maps should range from 0 to 1 (or 0 to 255 for the png). This linearly interpolates in disparity space between the minimum disparity (1/far depth) and maximum disparity (1/near depth). So if you know `near` and `far` depth bounds used to generate the MPI, you should be able to recover meaningful depths from our disparity map `d` by calculating 
```
z = 1 / ((1-d) / far + d / near)
```
