### ISSUE TITLE
extensive GPU/memory usage with high resolution output

### ISSUE THREAD

**Issue by mwsunshine** [Fyusion/LLFF#29]
Hi, many thanks for your impressive work!

I come up with some questions that I might need your help  when I try to get the outputs with high-resolution. 

1. I notice that the net given has a basic resolution of 640x480x3( and 32 default depth planes). When the resolution is higher than this, patches will be used via cutting the whole image. I tried a resolution of 1280x960, it worked fine. However, if I increase the resolution upto e.g. 4032x3024, the memory used will be increased dramatically(out of memory in my case). 

Have you ever tried this case and met the same problem? Is it possible to generate an output with high resolution?

2. 
![net](https://user-images.githubusercontent.com/13763085/74333033-104a5800-4dd2-11ea-9c20-bd1bcd85ee98.PNG)

the image showed above is the net structure given in your paper. As for the tensor named nnup7, the output channel is 64. if using the maximum resolution of 640x480 and 32 default planes. the full size of nnup7 is 1x32x480x640x64(batch, planes, height, width, channel). As I test this net structure,  I find the GPU needed for this net is very large(greater than 10G). 

My question is that am I right about the size of nnup7? If I am right, how many GPU have your used?

**Comment by mwsunshine** [comment]
As for the second question, I would like to discribe my net in more details: to implement your 2x nearest neighbor upsampling for layer nnup7, I used tf.concat for layer conv6_2 and conv1_2. Then I applied slim.conv3d_transpose to do the 3d upsampling(since I could not find any other available 3D upsampling in tensorflow).

I think the improper 3D upsampling might account for the extensive GPU consumption. However I have no idea how to replace it. Could you please explain how you do the 3D nearest upsampling?

**Comment by bmild** [comment]
The best way I know how to do it is a combination of reshape+tile+reshape like this:
```        
def nn_up(net):
            sh = tf.shape(net)
            ch = net.get_shape().as_list()[-1]
            net = tf.reshape(net, [sh[0], sh[1], 1, sh[2], 1, sh[3], 1, sh[4]])
            net = tf.tile(net, [1,1,2,1,2,1,2,1])
            net = tf.reshape(net, [sh[0], sh[1]*2, sh[2]*2, sh[3]*2, ch])
            return net
```
And you are correct that the nnup7 layer is very large, I believe it takes about 2GB of memory alone. That's the largest layer. We find that at 640x480x32 resolution it just barely fits into an 11GB GPU for training+test.

**Comment by mwsunshine** [comment]
> The best way I know how to do it is a combination of reshape+tile+reshape like this:
> 
> ```
> def nn_up(net):
>             sh = tf.shape(net)
>             ch = net.get_shape().as_list()[-1]
>             net = tf.reshape(net, [sh[0], sh[1], 1, sh[2], 1, sh[3], 1, sh[4]])
>             net = tf.tile(net, [1,1,2,1,2,1,2,1])
>             net = tf.reshape(net, [sh[0], sh[1]*2, sh[2]*2, sh[3]*2, ch])
>             return net
> ```
> 
> And you are correct that the nnup7 layer is very large, I believe it takes about 2GB of memory alone. That's the largest layer. We find that at 640x480x32 resolution the whole network just barely fits into an 11GB GPU for training+test.

hi， bmild,

This is pretty cool to do it in this way and as you said the GPU used in my case is also about 11GB. Thank you for your information!

This question will be closed.
