### ISSUE TITLE
glviewer

### ISSUE THREAD

**Issue by fpaboim** [Fyusion/LLFF#3]
Got a black screen viewing the results on glviewer, everything seemed fine so I looked at the code and uncommenting out the line 455 on viewer.cpp:
```
view = glm::lookAt(glm::vec3(0,0,0), glm::vec3(0,0,-1), glm::vec3(0,1,0));
```
fixes it for me, in case anyone has the same problem.

Would be cool to have access to generating the synthetic data and training at some point, if you guys decide to release that.

Awesome work! Waiting for LLFFvid ;)

**Comment by rodrygojose** [comment]
Hi @fpaboim 
thanks for testing the code. In the latest version of MacOS, OpenGL initializes a context with a black screen until one drag or resize the window. Thus in the OpenGL viewer, now it is possible to drag the window to solve that problem :-)

Regarding the code to generate the synthetic data and training, we are not planning to release that. 
:(

**Comment by Schizo** [comment]
I'm on Ubuntu 18.04 LTS and when running the opengl viewer as described in the `readme` I'm still getting a black Frame, even after uncommenting L:455. Any Ideas?
