### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by AlbertHuyb** [Fyusion/LLFF#35]
https://github.com/Fyusion/LLFF/blob/master/llff/inference/mpi_utils.py#L146

`neighs = neighs[1:]` should be `neighs = list(neighs[1:])`

otherwise `neighs += [i] * (5 - len(neighs))` in L148  would produce

`np.array([neighs[0]+i, neighs[1]+i, neighs[2]+i, neighs[3]+i])`

rather than 

`[neighs[0], neighs[1], neighs[2], neighs[3], i]`

However, it seems that this bug doesn't affect the inference result too much.

**Comment by bmild** [comment]
Thanks! fixed.
