### ISSUE TITLE
why does it only load the first camera params in load_colmap_data? There are numbers of cameras in raw colmap file "cameras.bin" 

### ISSUE THREAD

**Issue by seekever** [Fyusion/LLFF#57]
https://github.com/Fyusion/LLFF/blob/c6e27b1ee59cb18f054ccb0f87a90214dbe70482/llff/poses/pose_utils.py#L18

**Comment by rodrygojose** [comment]
It assumes all cameras have the same intrinsics. Thus there is only one set of camera intrinsic parameters

**Comment by seekever** [comment]
> It assumes all cameras have the same intrinsics. Thus there is only one set of camera intrinsic parameters

Got it. Thanks very much~~~
