### ISSUE TITLE
how to generate the database.db

### ISSUE THREAD

**Issue by Lvhhhh** [Fyusion/LLFF#7]
i have download the testscene.zip and trained model you provided in the right place.
when i run the command "python imgs2poses.py /home/lvhao/LLFF-master/data/testscene/"
it occur error:
Need to run COLMAP
Traceback (most recent call last):
  File "imgs2poses.py", line 11, in <module>
    gen_poses(args.scenedir)
  File "/home/lvhao/LLFF-master/llff/poses/pose_utils.py", line 265, in gen_poses
    run_colmap(basedir)
  File "/home/lvhao/LLFF-master/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

when i debug it , i found i dont have the '/home/lvhao/LLFF-master/data/testscene/database.db' .how to generate the database.db or can you offer it as it not in the  testscene.zip.thank you for your time

**Comment by bmild** [comment]
COLMAP should be initializing the database.db file on its own, as long as the directory you are passing exists and has an images folder.

Can you try running the COLMAP feature extractor command directly in the terminal to see if it works there? Something like this:
```
export SCENEDIR=/home/lvhao/LLFF-master/data/testscene
colmap feature_extractor --database_path $SCENEDIR/database.db --image_path $SCENEDIR/images --ImageReader.single_camera 1
```

Another potential issue could be if you're using the Dockerfile. If so, then root `/` on your drive will be mapped to `/host` inside the container, so you would have to use `/host/home/lvhao/LLFF-master/data/testscene/` as the path. 
Alternatively, you can just use a relative path, for example, simply `data/testscene/` when running from your LLFF-master base directory.

**Comment by Lvhhhh** [comment]
> COLMAP should be initializing the database.db file on its own, as long as the directory you are passing exists and has an images folder.
> 
> Can you try running the COLMAP feature extractor command directly in the terminal to see if it works there? Something like this:
> 
> ```
> export SCENEDIR=/home/lvhao/LLFF-master/data/testscene
> colmap feature_extractor --database_path $SCENEDIR/database.db --image_path $SCENEDIR/images --ImageReader.single_camera 1
> ```
> 
> Another potential issue could be if you're using the Dockerfile. If so, then root `/` on your drive will be mapped to `/host` inside the container, so you would have to use `/host/home/lvhao/LLFF-master/data/testscene/` as the path.
> Alternatively, you can just use a relative path, for example, simply `data/testscene/` when running from your LLFF-master base directory.

thank you .it works
